# Generated by Django 3.2 on 2021-12-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('topic1', 'Topic1'), ('topic2', 'Topic2'), ('topic3', 'Topic3'), ('topic4', 'Topic4'), ('topic5', 'Topic5')], default='topic1', max_length=50),
        ),
    ]
