# Generated by Django 3.2 on 2021-12-16 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_post_posttime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-postTime']},
        ),
    ]
