# Generated by Django 3.2 on 2021-12-16 15:19

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.ImageField(upload_to=api.models.upload_to, verbose_name='Image'),
        ),
    ]
