# Generated by Django 3.2 on 2021-12-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_post_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('topic1', 'topic1'), ('topic2', 'topic2'), ('topic3', 'topic3'), ('topic4', 'topic4'), ('topic5', 'topic5')], default='topic1', max_length=50),
        ),
    ]
