# Generated by Django 3.2 on 2021-12-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postTime',
            field=models.DateTimeField(),
        ),
    ]
