# Generated by Django 3.2 on 2021-12-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_post_posttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('Football', 'Football'), ("Men's Basketball", "Men's Basketball"), ("Women's basketball", "Women's basketball"), ('Softball', 'Softball'), ('Baseball', 'Baseball'), ('Campus', 'Campus')], default='Football', max_length=50),
        ),
    ]
