# Generated by Django 3.2 on 2021-12-18 00:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211217_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to, verbose_name='Image'),
        ),
    ]
