# Generated by Django 3.2 on 2021-12-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_post_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postLink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
